### Libraries for reading in data

In [1]:
import pandas as pd
import os
import numpy as np
notebook_directory = os.getcwd()
print(f'Current notebook directory: {notebook_directory}')

Current notebook directory: c:\Users\Matth\Desktop\repos\CollabProject

# NBA Player Box Scores 2024-2025 data

This dataset contains 736 NBA player-games from the 2024-2025 season, with several stats per each player-game. There are 440 unique players in this dataset.

In [2]:
box_score_data_path = os.path.join(notebook_directory,'data','NBA-BoxScores-2024-2025.csv')
df_boxscores = pd.read_csv(box_score_data_path)
np.shape(df_boxscores)

(736, 30)

In [3]:
df_boxscores.head() # looks like this consists of player-games of the 2024 to 2025 NBA seasons

,Unnamed: 0,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_CITY,PLAYER_ID,PLAYER_NAME,NICKNAME,START_POSITION,COMMENT,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,0,22400061,1610612752,NYK,New York,1628384,OG Anunoby,OG,F,NaN,...,0.0,5.0,5.0,3.0,1.0,0.0,0.0,3.0,4.0,-21.0
1,1,22400061,1610612752,NYK,New York,1628404,Josh Hart,Josh,F,NaN,...,1.0,3.0,4.0,3.0,0.0,0.0,1.0,0.0,12.0,-23.0
2,2,22400061,1610612752,NYK,New York,1626157,Karl-Anthony Towns,Karl-Anthony,C,NaN,...,0.0,7.0,7.0,3.0,0.0,0.0,0.0,1.0,12.0,-18.0
3,3,22400061,1610612752,NYK,New York,1628969,Mikal Bridges,Mikal,G,NaN,...,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,16.0,-33.0
4,4,22400061,1610612752,NYK,New York,1628973,Jalen Brunson,Jalen,G,NaN,...,0.0,1.0,1.0,2.0,0.0,0.0,4.0,3.0,22.0,-23.0

In [4]:
# player stats in this span
columns_to_exclue = ['Unnamed: 0', 'GAME_ID','TEAM_ID','PLAYER_ID']
player_stats = df_boxscores.groupby(by='PLAYER_NAME').agg("mean", numeric_only=True).drop(columns=columns_to_exclue)
player_stats.insert(0,'TEAM',df_boxscores.groupby(by='PLAYER_NAME')['TEAM_ABBREVIATION'].unique())
print(player_stats.shape)
player_stats.sample(10)

(440, 20)

,TEAM,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
PLAYER_NAME,,,,,,,,,,,,,,,,,,,,
Ajay Mitchell,[OKC],0.0,3.0,0.0000,0.0,1.0,0.0000,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,-1.0
Ricky Council IV,[PHI],0.5,2.0,0.2500,0.5,1.0,0.5000,2.0,2.0,0.5,0.0,0.5,0.5,0.0,0.0,0.0,0.5,0.5,3.5,0.0
Neemias Queta,[BOS],2.5,3.5,0.3570,0.0,0.5,0.0000,1.0,1.0,0.5,2.0,1.5,3.5,0.0,0.0,0.0,0.5,2.5,6.0,1.5
Jazian Gortman,[DAL],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Drew Peterson,[BOS],0.0,0.0,0.0000,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,2.0,1.0,0.0,0.0,-7.0
Simone Fontecchio,[DET],0.5,4.0,0.1250,0.5,3.0,0.1250,1.0,1.0,0.5,0.5,1.0,1.5,0.0,0.0,0.0,1.0,1.5,2.5,-1.0
Davion Mitchell,[TOR],3.5,7.5,0.5000,1.0,3.5,0.2500,0.0,0.0,0.0,0.0,1.5,1.5,3.0,1.0,0.0,4.0,3.0,8.0,-7.5
Leonard Miller,[MIN],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Christian Braun,[DEN],8.0,15.0,0.5330,0.0,3.0,0.0000,0.0,0.0,0.0,2.0,5.0,7.0,1.0,2.0,2.0,3.0,1.0,16.0,8.0
Marcus Smart,[MEM],2.0,7.5,0.2615,1.0,3.5,0.5835,4.0,4.5,0.9,1.5,1.5,3.0,1.5,1.0,0.0,2.0,3.5,9.0,-10.0

In [5]:
# team stats in this span
columns_to_exclue = ['Unnamed: 0', 'GAME_ID','PLAYER_ID','TEAM_ID']
round(df_boxscores.groupby(by='TEAM_ABBREVIATION').agg("mean", numeric_only=True).drop(columns=columns_to_exclue),3).sample(10)

,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
TEAM_ABBREVIATION,,,,,,,,,,,,,,,,,,,
WAS,2.929,6.786,0.362,0.500,2.571,0.063,0.929,1.286,0.304,0.714,2.143,2.857,1.929,0.643,0.429,0.929,1.357,7.286,-7.143
DEN,2.500,7.000,0.240,0.500,2.714,0.086,0.714,1.000,0.286,1.214,2.857,4.071,2.071,0.786,0.500,1.071,0.857,6.214,-5.357
IND,3.074,6.148,0.476,0.444,2.259,0.116,1.296,1.667,0.446,0.593,2.074,2.667,2.222,0.667,0.519,1.111,1.741,7.889,-3.519
DAL,3.231,7.846,0.387,1.462,3.385,0.252,1.308,1.769,0.354,1.308,2.538,3.846,2.077,0.692,0.385,0.692,1.615,9.231,4.231
HOU,3.522,8.739,0.385,1.304,3.739,0.292,1.783,2.435,0.373,1.696,2.957,4.652,1.696,0.783,0.348,1.087,2.174,10.130,3.261
ORL,3.077,6.577,0.396,1.269,3.038,0.377,1.500,2.115,0.422,0.885,2.808,3.692,2.154,0.692,0.577,0.885,1.538,8.923,6.538
SAS,3.000,6.615,0.382,0.923,2.769,0.265,1.462,1.846,0.356,0.923,3.077,4.000,2.308,0.462,0.385,1.462,1.385,8.385,-4.231
LAC,4.200,9.200,0.501,0.800,2.900,0.287,2.100,3.000,0.390,1.300,3.800,5.100,2.700,0.900,0.100,2.100,2.900,11.300,-1.500
MIN,4.222,9.500,0.396,1.833,5.056,0.278,1.944,2.444,0.517,1.000,3.944,4.944,2.278,0.389,0.167,1.722,2.556,12.222,-1.389
NYK,3.625,6.750,0.421,0.958,2.375,0.322,1.458,1.875,0.374,0.667,2.542,3.208,1.625,0.292,0.292,0.917,1.250,9.667,0.417

# 2025 Team Stats data

This dataset contains NBA team stats for the 2024-2025 season.

In [6]:
team_stats2_data_path = os.path.join(notebook_directory,'data','2025teamstats.csv')
df_teamstats2025 = pd.read_csv(team_stats2_data_path)
np.shape(df_teamstats2025)

(31, 25)

In [173]:
df_teamstats2025.columns

Index(['Rk', 'Team', 'G', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P',
       '2PA', '2P%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [7]:
df_teamstats2025.head()

,Rk,Team,G,MP,FG,FGA,FG%,3P,3PA,3P%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1.0,Cleveland Cavaliers,57,240.0,45.1,90.6,0.498,16.1,41.2,0.391,...,0.783,10.8,34.4,45.2,29.1,8.4,4.4,13.2,18.6,122.9
1,2.0,Memphis Grizzlies,57,240.0,45.0,93.3,0.482,13.9,37.5,0.372,...,0.769,13.3,34.4,47.7,28.9,9.0,6.0,16.5,21.3,122.8
2,3.0,Denver Nuggets,57,241.8,45.7,90.0,0.508,12.0,31.6,0.381,...,0.776,11.3,34.6,45.9,31.2,8.2,4.7,14.3,17.5,121.3
3,4.0,Oklahoma City Thunder,56,240.0,44.0,92.4,0.476,14.1,38.8,0.363,...,0.823,11.0,33.6,44.5,26.5,10.9,5.7,12.0,20.4,118.3
4,5.0,New York Knicks,57,241.8,44.0,89.3,0.493,12.8,34.1,0.374,...,0.805,10.8,32.2,42.9,27.5,7.9,3.8,13.1,16.9,117.9

# NBA Games 1946 - Present data

This datasets contains game information data on every NBA game, going back to 1946.

In [8]:
# dataset - https://www.kaggle.com/datasets/eoinamoore/historical-nba-data-and-player-box-scores/
team_stats_data_path = os.path.join(notebook_directory,'data','TeamStatistics.csv')
df_teams = pd.read_csv(team_stats_data_path)
np.shape(df_teams)

(142836, 48)

In [9]:
df_teams.columns

Index(['gameId', 'gameDate', 'teamCity', 'teamName', 'teamId',
       'opponentTeamCity', 'opponentTeamName', 'opponentTeamId', 'home', 'win',
       'teamScore', 'opponentScore', 'assists', 'blocks', 'steals',
       'fieldGoalsAttempted', 'fieldGoalsMade', 'fieldGoalsPercentage',
       'threePointersAttempted', 'threePointersMade',
       'threePointersPercentage', 'freeThrowsAttempted', 'freeThrowsMade',
       'freeThrowsPercentage', 'reboundsDefensive', 'reboundsOffensive',
       'reboundsTotal', 'foulsPersonal', 'turnovers', 'plusMinusPoints',
       'numMinutes', 'q1Points', 'q2Points', 'q3Points', 'q4Points',
       'benchPoints', 'biggestLead', 'biggestScoringRun', 'leadChanges',
       'pointsFastBreak', 'pointsFromTurnovers', 'pointsInThePaint',
       'pointsSecondChance', 'timesTied', 'timeoutsRemaining', 'seasonWins',
       'seasonLosses', 'coachId'],
      dtype='object')

In [10]:
df_teams.head() # quick look at the data

,gameId,gameDate,teamCity,teamName,teamId,opponentTeamCity,opponentTeamName,opponentTeamId,home,win,...,leadChanges,pointsFastBreak,pointsFromTurnovers,pointsInThePaint,pointsSecondChance,timesTied,timeoutsRemaining,seasonWins,seasonLosses,coachId
0,22400627,2025-03-19 21:00:00,Utah,Jazz,1610612762,Washington,Wizards,1610612764,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,32.0,NaN
1,22400627,2025-03-19 21:00:00,Washington,Wizards,1610612764,Utah,Jazz,1610612762,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,36.0,NaN
2,22400828,2025-02-24 22:00:00,Sacramento,Kings,1610612758,Charlotte,Hornets,1610612766,1,1,...,1.0,31.0,30.0,50.0,19.0,1.0,1.0,29.0,28.0,NaN
3,22400828,2025-02-24 22:00:00,Charlotte,Hornets,1610612766,Sacramento,Kings,1610612758,0,0,...,1.0,10.0,13.0,38.0,12.0,1.0,0.0,14.0,42.0,NaN
4,22400827,2025-02-24 21:00:00,Portland,Trail Blazers,1610612757,Utah,Jazz,1610612762,0,1,...,8.0,15.0,23.0,54.0,18.0,4.0,0.0,25.0,33.0,NaN

In [11]:
df_teams.coachId.unique() # nothing in coach id column. We'll get rid of it.
df_teams = df_teams.drop(columns=['coachId'])

In [12]:
# checking what is redundant across rows of same game
df_teams.loc[2240:2241,].T # we should check for NaNs

                                        2240                 2241
gameId                              22301095             22301095
gameDate                 2024-04-02 19:00:00  2024-04-02 19:00:00
teamCity                           Milwaukee           Washington
teamName                               Bucks              Wizards
teamId                            1610612749           1610612764
opponentTeamCity                  Washington            Milwaukee
opponentTeamName                     Wizards                Bucks
opponentTeamId                    1610612764           1610612749
home                                       0                    1
win                                        0                    1
teamScore                                113                  117
opponentScore                            117                  113
assists                                 31.0                 26.0
blocks                                   6.0                  2.0
steals                                   8.0                  9.0
fieldGoalsAttempted                    103.0                 93.0
fieldGoalsMade                          45.0                 47.0
fieldGoalsPercentage                   0.437                0.505
threePointersAttempted                  48.0                 38.0
threePointersMade                       11.0                  9.0
threePointersPercentage                0.229                0.237
freeThrowsAttempted                     18.0                 17.0
freeThrowsMade                          12.0                 14.0
freeThrowsPercentage                   0.667                0.824
reboundsDefensive                       39.0                 39.0
reboundsOffensive                       18.0                  5.0
reboundsTotal                           57.0                 44.0
foulsPersonal                           17.0                 20.0
turnovers                               12.0                 11.0
plusMinusPoints                         -4.0                  4.0
numMinutes                             240.0                240.0
q1Points                                 NaN                  NaN
q2Points                                 NaN                  NaN
q3Points                                 NaN                  NaN
q4Points                                 NaN                  NaN
benchPoints                              NaN                  NaN
biggestLead                              NaN                  NaN
biggestScoringRun                        NaN                  NaN
leadChanges                              NaN                  NaN
pointsFastBreak                          NaN                  NaN
pointsFromTurnovers                      NaN                  NaN
pointsInThePaint                         NaN                  NaN
pointsSecondChance                       NaN                  NaN
timesTied                                NaN                  NaN
timeoutsRemaining                        NaN                  NaN
seasonWins                               NaN                  NaN
seasonLosses                             NaN                  NaN

Missingness of df_teams

In [13]:
# missing percentage per column
cols_without_missing = []
for col in df_teams.columns:
    missing_percent = df_teams[col].isna().sum()/len(df_teams)
    if missing_percent > 0.30:
        print(col, missing_percent)
        cols_without_missing.append(False)
    else: 
        cols_without_missing.append(True)

cols_without_missing

q1Points 0.9872021059116749
q2Points 0.9872021059116749
q3Points 0.9872161079839816
q4Points 0.9872161079839816
benchPoints 0.9871881038393683
biggestLead 0.9871881038393683
biggestScoringRun 0.9871881038393683
leadChanges 0.9871881038393683
pointsFastBreak 0.9871881038393683
pointsFromTurnovers 0.9871881038393683
pointsInThePaint 0.9871881038393683
pointsSecondChance 0.9871881038393683
timesTied 0.9871881038393683
timeoutsRemaining 0.9871881038393683
seasonWins 0.9871881038393683
seasonLosses 0.9871881038393683

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False]

# Games.csv data

This data also contains information on every NBA game. It has slightly different information than the previous data. Each row is a game, which specifies the home and away teams. This is different than the previous dataset, which has two rows for each game.

In [14]:
games_data_path = os.path.join(notebook_directory,'data','Games.csv')
df_games = pd.read_csv(games_data_path)
np.shape(df_games)
# len(df_games.gameId.unique())

C:\Users\Matth\AppData\Local\Temp\ipykernel_21280\900250138.py:2: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  df_games = pd.read_csv(games_data_path)

(71418, 17)

In [15]:
df_games.sample(10)

,gameId,gameDate,hometeamCity,hometeamName,hometeamId,awayteamCity,awayteamName,awayteamId,homeScore,awayScore,winner,gameType,attendance,arenaId,gameLabel,gameSubLabel,seriesGameNumber
16292,21200990,2013-03-17 19:30:00,Dallas,Mavericks,1610612742,Oklahoma City,Thunder,1610612760,101,107,1610612760,Regular Season,20284.0,193,NaN,NaN,NaN
11308,21600304,2016-12-05 19:00:00,Philadelphia,76ers,1610612755,Denver,Nuggets,1610612743,98,106,1610612743,Regular Season,11815.0,419,NaN,NaN,NaN
54946,28000572,1981-01-22 20:00:00,San Diego,Clippers,1610612746,New York,Knicks,1610612752,93,100,1610612752,Regular Season,9797.0,100,NaN,NaN,NaN
37630,29600411,1996-12-29 19:00:00,Milwaukee,Bucks,1610612749,Miami,Heat,1610612748,94,95,1610612748,Regular Season,16235.0,5,NaN,NaN,NaN
54918,28000601,1981-01-27 20:00:00,Atlanta,Hawks,1610612737,Washington,Bullets,1610612764,104,105,1610612764,Regular Season,7090.0,41,NaN,NaN,NaN
39141,29500154,1995-11-24 20:00:00,Detroit,Pistons,1610612765,Philadelphia,76ers,1610612755,101,78,1610612765,Regular Season,16960.0,44,NaN,NaN,NaN
62986,27100712,1971-11-16 19:00:00,Detroit,Pistons,1610612765,Golden State,Warriors,1610612744,101,122,1610612744,Regular Season,4574.0,0,NaN,NaN,NaN
46671,28800792,1989-03-18 20:00:00,Milwaukee,Bucks,1610612749,Detroit,Pistons,1610612765,117,100,1610612749,Regular Season,18633.0,5,NaN,NaN,NaN
57310,27800106,1978-11-03 20:00:00,Philadelphia,76ers,1610612755,Milwaukee,Bucks,1610612749,118,103,1610612755,Regular Season,13297.0,12,NaN,NaN,NaN
46848,28800620,1989-02-19 20:00:00,Milwaukee,Bucks,1610612749,Chicago,Bulls,1610612741,106,108,1610612741,Regular Season,18633.0,5,NaN,NaN,NaN

### It looks like the TeamStatistics.csv and the Games.csv can be combined.

In [16]:
df_games.columns[df_games.columns.isin(df_teams.columns)] # both datasets with games have a game ID and a game date

Index(['gameId', 'gameDate'], dtype='object')

In [18]:
df_teams.columns[~df_teams.columns.isin(df_games.columns)] # columns of df_teams NOT in df_games

Index(['teamCity', 'teamName', 'teamId', 'opponentTeamCity',
       'opponentTeamName', 'opponentTeamId', 'home', 'win', 'teamScore',
       'opponentScore', 'assists', 'blocks', 'steals', 'fieldGoalsAttempted',
       'fieldGoalsMade', 'fieldGoalsPercentage', 'threePointersAttempted',
       'threePointersMade', 'threePointersPercentage', 'freeThrowsAttempted',
       'freeThrowsMade', 'freeThrowsPercentage', 'reboundsDefensive',
       'reboundsOffensive', 'reboundsTotal', 'foulsPersonal', 'turnovers',
       'plusMinusPoints', 'numMinutes', 'q1Points', 'q2Points', 'q3Points',
       'q4Points', 'benchPoints', 'biggestLead', 'biggestScoringRun',
       'leadChanges', 'pointsFastBreak', 'pointsFromTurnovers',
       'pointsInThePaint', 'pointsSecondChance', 'timesTied',
       'timeoutsRemaining', 'seasonWins', 'seasonLosses'],
      dtype='object')

In [139]:
df_games.columns[~df_games.columns.isin(df_teams.columns)] # columns of df_games NOT in df_teams

Index(['hometeamCity', 'hometeamName', 'hometeamId', 'awayteamCity',
       'awayteamName', 'awayteamId', 'homeScore', 'awayScore', 'winner',
       'gameType', 'attendance', 'arenaId', 'gameLabel', 'gameSubLabel',
       'seriesGameNumber'],
      dtype='object')

In [140]:
print(df_games.shape)
df_games.head()

(71418, 17)

,gameId,gameDate,hometeamCity,hometeamName,hometeamId,awayteamCity,awayteamName,awayteamId,homeScore,awayScore,winner,gameType,attendance,arenaId,gameLabel,gameSubLabel,seriesGameNumber
0,22400627,2025-03-19 21:00:00,Utah,Jazz,1610612762,Washington,Wizards,1610612764,0,0,1610612764,Regular Season,NaN,1000106,NaN,NaN,0.0
1,22400828,2025-02-24 22:00:00,Sacramento,Kings,1610612758,Charlotte,Hornets,1610612766,130,88,1610612758,Regular Season,17832.0,609,NaN,NaN,0.0
2,22400827,2025-02-24 21:00:00,Utah,Jazz,1610612762,Portland,Trail Blazers,1610612757,112,114,1610612757,Regular Season,18175.0,1000106,NaN,NaN,0.0
3,22400826,2025-02-24 20:00:00,Oklahoma City,Thunder,1610612760,Minnesota,Timberwolves,1610612750,128,131,1610612750,Regular Season,18203.0,1000052,NaN,NaN,0.0
4,22400825,2025-02-24 19:30:00,Atlanta,Hawks,1610612737,Miami,Heat,1610612748,98,86,1610612737,Regular Season,16189.0,650,NaN,NaN,0.0

In [141]:
print(df_teams.shape)
df_teams.head()

(142836, 47)

,gameId,gameDate,teamCity,teamName,teamId,opponentTeamCity,opponentTeamName,opponentTeamId,home,win,...,biggestScoringRun,leadChanges,pointsFastBreak,pointsFromTurnovers,pointsInThePaint,pointsSecondChance,timesTied,timeoutsRemaining,seasonWins,seasonLosses
0,22400627,2025-03-19 21:00:00,Utah,Jazz,1610612762,Washington,Wizards,1610612764,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,32.0
1,22400627,2025-03-19 21:00:00,Washington,Wizards,1610612764,Utah,Jazz,1610612762,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,36.0
2,22400828,2025-02-24 22:00:00,Sacramento,Kings,1610612758,Charlotte,Hornets,1610612766,1,1,...,14.0,1.0,31.0,30.0,50.0,19.0,1.0,1.0,29.0,28.0
3,22400828,2025-02-24 22:00:00,Charlotte,Hornets,1610612766,Sacramento,Kings,1610612758,0,0,...,9.0,1.0,10.0,13.0,38.0,12.0,1.0,0.0,14.0,42.0
4,22400827,2025-02-24 21:00:00,Portland,Trail Blazers,1610612757,Utah,Jazz,1610612762,0,1,...,18.0,8.0,15.0,23.0,54.0,18.0,4.0,0.0,25.0,33.0

In [19]:
df_teams = df_teams[df_teams.columns[cols_without_missing]]

In [20]:
df_teams.head()

,gameId,gameDate,teamCity,teamName,teamId,opponentTeamCity,opponentTeamName,opponentTeamId,home,win,...,freeThrowsAttempted,freeThrowsMade,freeThrowsPercentage,reboundsDefensive,reboundsOffensive,reboundsTotal,foulsPersonal,turnovers,plusMinusPoints,numMinutes
0,22400627,2025-03-19 21:00:00,Utah,Jazz,1610612762,Washington,Wizards,1610612764,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,22400627,2025-03-19 21:00:00,Washington,Wizards,1610612764,Utah,Jazz,1610612762,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,22400828,2025-02-24 22:00:00,Sacramento,Kings,1610612758,Charlotte,Hornets,1610612766,1,1,...,18.0,16.0,0.889,38.0,11.0,49.0,18.0,18.0,42.0,240.0
3,22400828,2025-02-24 22:00:00,Charlotte,Hornets,1610612766,Sacramento,Kings,1610612758,0,0,...,24.0,18.0,0.750,22.0,15.0,37.0,16.0,19.0,-42.0,240.0
4,22400827,2025-02-24 21:00:00,Portland,Trail Blazers,1610612757,Utah,Jazz,1610612762,0,1,...,24.0,18.0,0.750,35.0,16.0,51.0,16.0,13.0,2.0,240.0

In [182]:
df_teams_home = df_teams[df_teams.home == 1]
print(df_teams_home.shape)

(71418, 47)

In [183]:
df_teams_away = df_teams[df_teams.home == 0]
print(df_teams_away.shape)

(71418, 47)

In [ ]:
df_teams1 = df_teams[df_teams.index % 2 == 0]
print(df_teams1.shape)
df_teams1.head()

In [ ]:
df_teams2 = df_teams[df_teams.index % 2 == 1]
df_teams2.head()

In [184]:
df_games1 = df_teams_home.merge(right=df_teams_away,how='inner',on='gameId',suffixes=('_home','_away'))
print(df_games1.shape)
df_games1.head()

(71418, 93)

,gameId,gameDate_home,teamCity_home,teamName_home,teamId_home,opponentTeamCity_home,opponentTeamName_home,opponentTeamId_home,home_home,win_home,...,biggestScoringRun_away,leadChanges_away,pointsFastBreak_away,pointsFromTurnovers_away,pointsInThePaint_away,pointsSecondChance_away,timesTied_away,timeoutsRemaining_away,seasonWins_away,seasonLosses_away
0,22400627,2025-03-19 21:00:00,Utah,Jazz,1610612762,Washington,Wizards,1610612764,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,36.0
1,22400828,2025-02-24 22:00:00,Sacramento,Kings,1610612758,Charlotte,Hornets,1610612766,1,1,...,9.0,1.0,10.0,13.0,38.0,12.0,1.0,0.0,14.0,42.0
2,22400827,2025-02-24 21:00:00,Utah,Jazz,1610612762,Portland,Trail Blazers,1610612757,1,0,...,18.0,8.0,15.0,23.0,54.0,18.0,4.0,0.0,25.0,33.0
3,22400826,2025-02-24 20:00:00,Oklahoma City,Thunder,1610612760,Minnesota,Timberwolves,1610612750,1,0,...,16.0,9.0,11.0,22.0,62.0,20.0,7.0,0.0,32.0,27.0
4,22400825,2025-02-24 19:30:00,Atlanta,Hawks,1610612737,Miami,Heat,1610612748,1,1,...,10.0,8.0,7.0,19.0,38.0,14.0,7.0,1.0,26.0,30.0

In [ ]:
df_games = df_games1.merge(right=df_games,how='inner',on='gameId',suffixes=('_teams','_games'))
print(df_games.shape)
df_games.head()

(71418, 77)

,gameId,gameDate_1,teamCity_1,teamName_1,teamId_1,opponentTeamCity_1,opponentTeamName_1,opponentTeamId_1,home_1,win_1,...,awayteamId,homeScore,awayScore,winner,gameType,attendance,arenaId,gameLabel,gameSubLabel,seriesGameNumber
0,22400627,2025-03-19 21:00:00,Utah,Jazz,1610612762,Washington,Wizards,1610612764,1,0,...,1610612764,0,0,1610612764,Regular Season,NaN,1000106,NaN,NaN,0.0
1,22400828,2025-02-24 22:00:00,Sacramento,Kings,1610612758,Charlotte,Hornets,1610612766,1,1,...,1610612766,130,88,1610612758,Regular Season,17832.0,609,NaN,NaN,0.0
2,22400827,2025-02-24 21:00:00,Portland,Trail Blazers,1610612757,Utah,Jazz,1610612762,0,1,...,1610612757,112,114,1610612757,Regular Season,18175.0,1000106,NaN,NaN,0.0
3,22400826,2025-02-24 20:00:00,Minnesota,Timberwolves,1610612750,Oklahoma City,Thunder,1610612760,0,1,...,1610612750,128,131,1610612750,Regular Season,18203.0,1000052,NaN,NaN,0.0
4,22400825,2025-02-24 19:30:00,Atlanta,Hawks,1610612737,Miami,Heat,1610612748,1,1,...,1610612748,98,86,1610612737,Regular Season,16189.0,650,NaN,NaN,0.0

In [49]:
import pandas as pda
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import warnings

from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score

ModuleNotFoundError: No module named 'seaborn'

In [ ]:
team1 = input("Enter Team 1:")
team2 = input("Enter Team 2:")

team1_df = df_teams[(df_teams['teamName'] == team1) & (df_teams['opponentTeamName'] == team2)]
team1_df

team2_df = df_teams[(df_teams['teamName'] == team2) & (df_teams['opponentTeamName'] == team1)]
team2_df

#model for team1
features = ['assists', 'blocks', 'steals', 'fieldGoalsMade', 'fieldGoalsPercentage', 'threePointersMade', 'freeThrowsMade', 'reboundsTotal', 'turnovers']
x = team1_df[features]
y = team1_df['teamScore']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(x_train, y_train)

#model for team2
features2 = ['assists', 'blocks', 'steals', 'fieldGoalsMade', 'fieldGoalsPercentage', 'threePointersMade', 'freeThrowsMade', 'reboundsTotal', 'turnovers']
x = team2_df[features]
y = team2_df['teamScore']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model2 = RandomForestRegressor(n_estimators=100, random_state=42)
model2.fit(x_train, y_train)

RandomForestRegressor(random_state=42)

In [ ]:
team1_score = team1_df[['assists', 'blocks', 'steals', 'fieldGoalsMade', 'fieldGoalsPercentage', 'threePointersMade', 'freeThrowsMade', 'reboundsTotal', 'turnovers']]
team2_score = team2_df[['assists', 'blocks', 'steals', 'fieldGoalsMade', 'fieldGoalsPercentage', 'threePointersMade', 'freeThrowsMade', 'reboundsTotal', 'turnovers']]

predicted_score1 = model.predict(team1_score)[0]
predicted_score2 = model2.predict(team2_score)[0]

print(f'{team1} Score: {predicted_score1}')
print(f'{team2} Score: {predicted_score2}')

Bulls Score: 107.29
Celtics Score: 122.48